### PR TITLE
Added possibility to fall back to a default user id

### PR DESCRIPTION
**Pull request by kerwitz**
As described in #9.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks, I'll review your changes this weekend. If all is good, I'll merge it and tag a new version.

**Comment by kerwitz** [comment]
:+1:

**Comment by freekmurze** [comment]
I've taken a look at your code a bit earlier than anticipated. In general your changes were good. I've refactored `normalizedUserId' a little bit. If prefer early returns over else-branches.

All changes are included in the newly tagged version 2.1.0

**Comment by kerwitz** [comment]
Looks good!

**Pull request merged**
